// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxakritdrcwopdwjmwke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4YWtyaXRkcmN3b3Bkd2ptd2tlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjc0NjIsImV4cCI6MjA2OTgwMzQ2Mn0.lpcVxI4h2PwLcMgTaL0yM9FUo9LoYOP1vdzxWAtIhL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});